package io.github.manoelcampos.dtogen.samples;

/**
 * A plain (non-DTO annotated) abstract base class that declares a private "id" field
 * with public getter/setter, emulating a superclass whose accessors are generated by Lombok
 * (such as an {@code AbstractBaseModel} using {@code @Getter}/{@code @Setter}).
 * It's used to check if the DTO generator recognizes accessors inherited from a superclass.
 * @author Manoel Campos
 */
@SuppressWarnings("unused")
public abstract class Class4 {
    private long id;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
}
